name: tody_list
packages:
  - 'packages/*'
  - 'apps/*'
enablePublish: false
scripts:
  run_app:
    run: melos exec --scope="main_app" -- flutter run
  get_all:
    run: melos exec -- flutter pub get
  analyze:
    run: melos exec -- flutter analyze .
  test:
    run: melos exec -- flutter test
  build_all:
    run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
  build_auth:
    run: melos exec --scope="auth" -- flutter pub run build_runner build --delete-conflicting-outputs
  watch_build:
    run: dart tool/watch_build.dart
  clean_all:
    run: |
      melos exec -- \
        "flutter clean && dart run ../../tool/clean.dart"
    description: Deep clean all Flutter packages and apps
